### ISSUE TITLE
I need dismiss EasyTipView in a superView

### ISSUE THREAD

**Issue by ban9ban3** [teodorpatras/EasyTipView#1]
What you think about this:

    class func hideAllInSuperView(sview: UIView) {
        for subview in sview.subviews {
            if subview is EasyTipView {
                let sub = subview as! EasyTipView      
          
                UIView.animateWithDuration(0.2, animations: { () -> Void in
                    sub.transform = CGAffineTransformMakeScale(0.3, 0.3)
                    sub.alpha = 0
                    }) { (finished) -> Void in
                        sub.removeFromSuperview()
                }
            }
        }
    }

**Comment by teodorpatras** [comment]
In order to dismiss an instance of ``EasyTipView`` programmatically you should call:

``func dismissWithCompletion(completion : ((finished : Bool) -> Void)?)``

If you do not keep any reference to your tip views displayed at any moment, you will have to loop through the subviews of the view in which the tip views have been displayed and then call ``dismissWithCompletion:`` to all instances:

```swift
for view in superview.subviews {
    if let tipView = view as? EasyTipView {
        tipView.dismissWithCompletion(nil)
    }
}
```

What I recommend though, in case you want to programmatically dismiss the tip view later, is to use this approach of presenting them (and thus keeping a reference to the tip view so that later you call ``dismissWithCompletion:``  on it) :

```swift
   // create and customize the preferences
   var preferences = EasyTipView.Preferences()
   preferences.bubbleColor = UIColor(hue:0.58, saturation:0.1, brightness:1, alpha:1)
   preferences.textColor = UIColor.darkGrayColor()
   preferences.font = UIFont(name: "HelveticaNeue-Regular", size: 10)
   preferences.textAlignment = NSTextAlignment.Center
   
 // create an instance of the tip view      
 myTipView = EasyTipView(text: "Tip view within the green superview. Tap to dismiss.", preferences: preferences, delegate: nil)
// present the view 
 myTipView.showForView(buttonA, withinSuperview: self.smallContainerView, animated: true)

 // and later on, dismiss it programmatically
 myTipView.dismissWithCompletion(nil)

```

**Comment by ban9ban3** [comment]
yeap! you Right!

**Comment by tnmendex** [comment]
This code is working with recent version of easytip?

**Comment by teodorpatras** [comment]
outdated. check readme for the new methods.
