### ISSUE TITLE
Detect tap on EasyTipView

### ISSUE THREAD

**Issue by andrey-lisovskiy** [teodorpatras/EasyTipView#101]
Is it possible, to detect tap on specific tipView for assigning action to it?

**Comment by mmdock** [comment]
Some ideas off the top of my head: 

You can probably make use of the tipViewDidDismiss delegate function since that occurs after the tap and dismiss.  You can unique identify the tipView from that through identifying the text it contains, although I would try modifying the show function to have a tag field and set the tag onto the view for convenience in the long term.

is there an easier way? Probably.

**Comment by thepinyo** [comment]
it should check dismissOnTap flag before call dismiss method in handleTap() method. please change logic for handle this case.

**Comment by teodorpatras** [comment]
Please check  version 2.1.0  🚀
